### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by natejones05** [nisabmohd/ChatGPT#14]
Error: Cannot find module '/home/projects/node-svljip/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /home/projects/node-svljip/node_modules/bcrypt/bcrypt.js
- /home/projects/node-svljip/controllers/auth.js
- /home/projects/node-svljip/routers/auth.js
- /home/projects/node-svljip/server.js
    at Module._resolveFilename (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:6:217309)
    at Module._load (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:6:214848)
    at Module.require (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:6:218088)
    at i (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:6:419512)
    at _0xd5330f (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:15:143696)
    at Object.eval (file:///home/projects/node-svljip/node_modules/bcrypt/bcrypt.js:6:16)
    at Object.function (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:15:144430)
    at Module._compile (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:6:219080)
    at Module._extensions..js (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:6:219744)
    at Module.load (https://nodesvljip-gzo0.w-credentialless.staticblitz.com/blitz.9bdac2de468a4854f7bacb85c771c93d5676829b.js:6:217770) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/projects/node-svljip/node_modules/bcrypt/bcrypt.js',
    '/home/projects/node-svljip/controllers/auth.js',
    '/home/projects/node-svljip/routers/auth.js',
    '/home/projects/node-svljip/server.js'
  ]
}

I have ran npm install and have tried to manually install it

**Comment by ghost** [comment]
what version of node.js you have?

**Comment by nisabmohd** [comment]
Please update your node version
