### ISSUE TITLE
Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by TheKryptoDev** [nisabmohd/ChatGPT#6]
Followed instructions properly, getting this error:

react-jsx-dev-runtime.development.js:87 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Messages`. See https://reactjs.org/link/warning-keys for more information.
    at Message (http://localhost:5173/src/components/Message.tsx:18:3)
    at Messages (http://localhost:5173/src/components/Messages.tsx:20:3)
    at div
    at div
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ffbdf1ee:2767:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ffbdf1ee:3098:5)
    at div
    at App (http://localhost:5173/src/App.tsx:27:35)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ffbdf1ee:3045:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ffbdf1ee:3458:5)
printWarning @ react-jsx-dev-runtime.development.js:87
:8000/chatgpt/chat/38160bca288b87cef52cce:1          Failed to load resource: the server responded with a status of 400 (Bad Request)

Cant find the cause.

**Comment by nisabmohd** [comment]
fixed that unique key prop 👍

**Comment by TheKryptoDev** [comment]
You're a star, bro!
